# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta9pwifi/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gta9pwifi

PRODUCT_COPY_FILES += \
    vendor/samsung/gta4lwifi/proprietary/vendor/firmware/wlan/qca_cld/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/bdwlan.bin \
    vendor/samsung/gta4lwifi/proprietary/vendor/firmware/wlan/qca_cld/grippower.info:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/grippower.info \
    vendor/samsung/gta4lwifi/proprietary/vendor/firmware/wlan/qca_cld/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/regdb.bin \
    vendor/samsung/gta4lwifi/proprietary/vendor/firmware/wlanmdsp_SM-X210.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/wlanmdsp_SM-X210.mbn
